#!/usr/bin/env ruby

require File.expand_path('../../config/application', __FILE__)
Bundler.require(:default, :console)

require 'config/application'

# include rack helpers to play around with
include Rack::Test::Methods
self.instance_eval do
  @app = Emotejiji::API.new
  def app; @app; end
end

# add ability to reload console
def reload
  reload_msg = '# Reloading the console...'
  puts CodeRay.scan(reload_msg, :ruby).term
  Pry.save_history
  Neo4j::shutdown #closes the db instances
  exec(__FILE__)
end
alias :reload! :reload

# start the console! :-)
system('clear')

welcome = <<eos
 Emotejiji Console
eos

puts CodeRay.scan(welcome, :ruby).term

Pry.start